// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

type Transaction struct {
	ID          int64
	Type        string
	AmountCents int64
	Date        string
	Category    string
	Description string
}
