// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
)

const createTransaction = `-- name: CreateTransaction :one

INSERT INTO transactions (type, amount_cents, date, category, description)
VALUES (?, ?, ?, ?, ?)
RETURNING id, type, amount_cents, date, category, description
`

type CreateTransactionParams struct {
	Type        string
	AmountCents int64
	Date        string
	Category    string
	Description string
}

// sqlc query definitions for the Budget Tracker transactions table.
func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, createTransaction,
		arg.Type,
		arg.AmountCents,
		arg.Date,
		arg.Category,
		arg.Description,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AmountCents,
		&i.Date,
		&i.Category,
		&i.Description,
	)
	return i, err
}

const deleteTransaction = `-- name: DeleteTransaction :exec
DELETE FROM transactions
WHERE id = ?
`

func (q *Queries) DeleteTransaction(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteTransaction, id)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, type, amount_cents, date, category, description
FROM transactions
WHERE id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, id int64) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, id)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AmountCents,
		&i.Date,
		&i.Category,
		&i.Description,
	)
	return i, err
}

const listTransactions = `-- name: ListTransactions :many
SELECT id, type, amount_cents, date, category, description
FROM transactions
ORDER BY date DESC, id ASC
`

func (q *Queries) ListTransactions(ctx context.Context) ([]Transaction, error) {
	rows, err := q.db.QueryContext(ctx, listTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Transaction{}
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.AmountCents,
			&i.Date,
			&i.Category,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTransaction = `-- name: UpdateTransaction :one
UPDATE transactions
SET type = ?, amount_cents = ?, date = ?, category = ?, description = ?
WHERE id = ?
RETURNING id, type, amount_cents, date, category, description
`

type UpdateTransactionParams struct {
	Type        string
	AmountCents int64
	Date        string
	Category    string
	Description string
	ID          int64
}

func (q *Queries) UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, updateTransaction,
		arg.Type,
		arg.AmountCents,
		arg.Date,
		arg.Category,
		arg.Description,
		arg.ID,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.AmountCents,
		&i.Date,
		&i.Category,
		&i.Description,
	)
	return i, err
}
